name: Check parked domains
run-name: Check parked domains
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
permissions:
  contents: write

jobs:
  get-files:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get script and parked terms
        run: |
          curl -sSL --retry 2 --retry-all-errors \
            "${{ vars.SCAM_BLOCKLIST_URL }}/scripts/check_parked.sh" \
            -o check_parked.sh

          curl -sSL --retry 2 --retry-all-errors \
            "${{ vars.SCAM_BLOCKLIST_URL }}/config/parked_terms.txt" \
            -o parked_terms.txt

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "$(date +"%d-%m-%Y")"
          git push -q

  check-unparked-domains:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check for unparked domains
        run: |
          curl -sSL --retry 2 --retry-all-errors \
            "${{ vars.SCAM_BLOCKLIST_URL }}/data/parked_domains.txt" \
            -o parked_domains.tmp

          bash check_parked.sh --check-unparked parked_domains.tmp

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "$(date +"%d-%m-%Y")"
          git push -q

  check-parked-part-1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check for parked domains (part 1)
        run: |
          curl -sSL --retry 2 --retry-all-errors \
            "${{ vars.SCAM_BLOCKLIST_URL }}/data/raw.txt" \
            -o raw.tmp

          bash check_parked.sh --check-parked-part-1 raw.tmp

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "$(date +"%d-%m-%Y")"
          git push -q

  check-parked-part-2:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check for parked domains (part 2)
        run: |
          curl -sSL --retry 2 --retry-all-errors \
            "${{ vars.SCAM_BLOCKLIST_URL }}/data/raw.txt" \
            -o raw.tmp

          bash check_parked.sh --check-parked-part-2 raw.tmp

      - name: Push
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
          git add .
          git diff-index --quiet HEAD || git commit -m "$(date +"%d-%m-%Y")"
          git push -q
